### PR TITLE
Build for all supported platforms

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
Tests pass. Ready for review

**Comment by isuruf** [comment]
ping

**Comment by isuruf** [comment]
ping again

**Comment by StefanKarpinski** [comment]
If someone who actually manages this repo doesn't reply and look at this PR soon, I'm just going to merge it even though I have NO idea what I'm doing. cc @ViralBShah, @staticfloat, @Keno

**Comment by isuruf** [comment]
Thanks

**Comment by isuruf** [comment]
Can you make a release from master?

**Comment by ViralBShah** [comment]
I've given you write permissions to this repo, if you are ok to make the release. Otherwise I will only get to it next week.

**Comment by isuruf** [comment]
Thanks. I just made a release.

**Pull request merged**
